language: python
python: 
	'3.6'

install:
    -pip install *
    -pip install --user -r requirement.txt
script:
    -pytest
    -nosetests
deploy:
	provider: pages
	skip_cleanup: true
	on:
		branch: master
after_success:coveralls