language: python

python: '3.6'

install: 
  - pip install -r requirements.txt
  ##-pip install coveralls

script:
  - python app.py
  - pytest
  - nosetest --exe -v
  - nosetest --exe --with-coverage --cover-package=app
  - coveralls

deploy:
  provider: heroku
  api_key: 0156b56a-0452-474d-850f-6aadb13649ea
  app:
    master: master

after_success: 
  - coveralls
  - change

